- name: Deploy initial config
  hosts: bb, rr, metro, headend
  gather_facts: false
  tasks:
    - name: Deploy config
      arista.eos.eos_config:
        src: initial/{{ inventory_hostname | upper }}.conf
